src/main/java/com/blog/personal/dto/UserDTO.java
package com.blog.personal.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.Date;

@Getter
@Setter
public class UserDTO implements UserDetails {

    private static final long serialVersionUID = -3217036007023129188L;

    @JsonIgnore
    private long userId;
    private String usernameLM;
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;
    private String locale;
    private boolean enabled;
    private boolean active;
    private String email;
    private Integer age;
    private Gender gender;
    private Collection<? extends GrantedAuthority> authorities;
    private String confirmationKey;
    @JsonIgnore
    private Date lastPasswordResetDate;

    @Override
    public String getUsername() {
        return email;
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return authorities;
    }

    @JsonIgnore
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @JsonIgnore
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @JsonIgnore
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }
}

src/main/java/com/blog/personal/model/Post.java
package com.blog.personal.model;

import lombok.Data;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
@Data
@Table(name = "posts")
public class Post {

    @Id
    @Column(name = "post_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int postId;

    @Column(name = "title")
    private String title;

    @Column(name = "body")
    private String body;

    @Column(name = "creation_date")
    private Date creationDate;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User user;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "post", cascade = CascadeType.REMOVE)
    private List<Tracking> trackingList;

    public Post() {
    }

    public Post(int postId) {
        this.postId = postId;
    }
}

src/main/webapp/resources/about.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<h2>{{'about.text' | translate}}</h2>

src/main/webapp/resources/admin.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="container">
    <div class="col-sm-12">

        <div class="bs-calltoaction bs-calltoaction-info">
            <div class="row">
                <div class="col-md-9 cta-contents">
                    <h1 class="cta-title">{{'admin.myPosts.title' | translate}}</h1>
                    <div class="cta-desc">
                        <p>{{'admin.myPosts.desc' | translate}}</p>
                    </div>
                </div>
                <div class="col-md-3 cta-button">
                    <a href="myposts" class="btn btn-lg btn-block btn-info">{{'admin.myPosts.btn' | translate}}</a>
                </div>
            </div>
        </div>

        <div class="bs-calltoaction bs-calltoaction-success">
            <div class="row">
                <div class="col-md-9 cta-contents">
                    <h1 class="cta-title">{{'admin.settings.title' | translate}}</h1>
                    <div class="cta-desc">
                        <p>{{'admin.settings.desc' | translate}}</p>
                    </div>
                </div>
                <div class="col-md-3 cta-button">
                    <a href="settings" class="btn btn-lg btn-block btn-success">{{'admin.settings.btn' | translate}}</a>
                </div>
            </div>
        </div>

        <div class="bs-calltoaction bs-calltoaction-warning">
            <div class="row">
                <div class="col-md-9 cta-contents">
                    <h1 class="cta-title">{{'admin.reports.title' | translate}}</h1>
                    <div class="cta-desc">
                        <p>{{'admin.reports.desc' | translate}}</p>
                    </div>
                </div>
                <div class="col-md-3 cta-button">
                    <a href="reports" class="btn btn-lg btn-block btn-warning">{{'admin.reports.btn' | translate}}</a>
                </div>
            </div>
        </div>

    </div>
</div>

src/main/webapp/resources/allposts.jsp
</div>
<h3>{{'posts.allPostsTitle' | translate}}</h3>
</div>

<div ng-repeat="blogPost in filteredPosts">
    <h4>{{'posts.creationDate' | translate}} {{blogPost.creationDate | date}}</h4>
    <p>{{'posts.author' | translate}} {{blogPost.user.usernameLM}}</p>
    <h4>{{'posts.title' | translate}} {{blogPost.title}}</h4>
    <p>{{blogPost.body}}</p>
    <a href="/post/{{blogPost.postId}}">View details &raquo;</a>
    <hr/>
</div>
<div>
    <pagination ng-show="amountOfAllPosts > numPerPage"
                ng-model="currentPage"
                total-items="totalPages"
                max-size="maxSize"
                boundary-links="true">
    </pagination>
</div>

src/main/webapp/resources/login.jsp
<div class="container" ng-controller="Login as log">
    <form class="form-horizontal" ng-submit="log.login()">
        <fieldset>

            <legend>{{'login.title' | translate}}</legend>
            <div class="alert alert-danger" ng-show="errorMessage">
                <div class="text-center"><strong>{{errorMessage}}</strong></div>
            </div>
            <div class="alert alert-danger" ng-show="successMessage">
                <div class="text-center"><strong>{{successMessage}}</strong></div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="email">{{'login.email.label' | translate}}</label>
                <div class="col-md-4">
                    <input id="email" name="email" type="email"
                           placeholder="{{'login.email.placeholder' | translate}}"
                           class="form-control input-md" required ng-model="log.email">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="passwordinput">{{'login.password.label' | translate}}</label>
                <div class="col-md-4">
                    <input id="passwordinput" name="passwordinput" type="password"
                           placeholder="{{'login.password.placeholder' | translate}}"
                           class="form-control input-md" required ng-model="log.password">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>
                <div class="col-md-4">
                    <input id="submit" name="submit" type="submit" value="{{'button.login' | translate}}"
                           class="btn btn-primary"/>
                </div>
            </div>

        </fieldset>
    </form>
</div>

src/main/webapp/resources/myposts.jsp
<div class="page-header" ng-controller="Main as main" >
    <div class="pull-right" ng-show="main.isActiveUser()">
        <a href="/post_editor" class="btn btn-default" title="Create">
            <span class="fa fa-plus"></span>
        </a>
    </div>
    <h3>{{'posts.myPostsTitle' | translate}}</h3>
</div>
<div ng-repeat="blogPost in filteredPosts" ng-controller="MyPosts as posts">
    <div class="pull-right">
        <button class="btn btn-xs btn-default" ng-click="posts.deletePost(blogPost.postId)"><span
                class="fa fa-trash-o fa-2x"></span></button>
        <a href="/post_editor/{{blogPost.postId}}" class="btn btn-xs btn-default" ng-show="!main.isAuthed(['Admin'])"
           title="edit"><span class="fa fa-pencil fa-2x"></span></a>
    </div>
    <h4>{{'posts.creationDate' | translate}} {{blogPost.creationDate | date}}</h4>
    <p>{{'posts.author' | translate}} {{blogPost.user.usernameLM}}</p>
    <h4>{{'posts.title' | translate}} {{blogPost.title}}</h4>
    <p>{{blogPost.body}}</p>
    <a href="/post/{{blogPost.postId}}">{{'myPosts.details' | translate}} &raquo;</a>
    <hr/>
</div>
<div>
    <pagination ng-show="amountOfAllPosts > numPerPage"
                ng-model="currentPage"
                total-items="totalPages"
                max-size="maxSize"
                boundary-links="true">
    </pagination>
</div>

src/main/webapp/resources/post.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="jumbotron">
    <div class="container" ng-controller="PostDetails as post">
        <div class="row">
            <div class="col-md-7">
                <h2>{{post.title}}</h2>
                <p>{{post.body}}</p>
            </div>
            <div class="col-md-3"><span class="pull-right">
                <h2>{{post.username}}</h2>
            </span>
            </div>
            <div class="col-md-2"><span class="pull-right"><h2>{{post.numberOfUniqueVisits}} <span class="glyphicon glyphicon-eye-open"></span></h2></span>
            </div>
        </div>
    </div>
</div>

src/main/webapp/resources/posteditor.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="container" ng-controller="PostEditorCtrl as pe">
    <div class="page-header">
        <h3>{{'postEditor.mainTitle' | translate}}</h3>
    </div>
    <form>
        <div class="form-group">
            <label for="title">{{'postEditor.title' | translate}}</label>
            <input id="title" class="form-control" type="text" ng-maxlength="255" ng-model="pe.title">
        </div>
        <div class="form-group">
            <label for="textbody">{{'postEditor.body' | translate}}</label>
            <textarea id="textbody" class="form-control" rows="5" maxlength="65025" ng-model="pe.body"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" ng-click="pe.save()"><span class="fa fa-check"></span>{{'button.save' | translate}}
            </button>
        </div>
    </form>
</div>

src/main/webapp/resources/reports.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="container" ng-controller="Reports as rep">
    <div class="row">
        <div class="col-md-12">
            <legend>{{'reports.numberVisits' | translate}}</legend>
            <div class="table-responsive">
                <table id="mytable" class="table table-bordred table-striped">
                    <thead>
                    <tr>
                        <th>{{'reports.table.postId' | translate}}</th>
                        <th>{{'reports.table.title' | translate}}</th>
                        <th>{{'reports.table.perToday' | translate}}</th>
                        <th>{{'reports.table.thisWeek' | translate}}</th>
                        <th>{{'reports.table.thisMonth' | translate}}</th>
                        <th>{{'reports.table.all' | translate}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr ng-repeat="numVis in rep.numberVisits">
                        <td>{{numVis[0]}}</td>
                        <td>{{numVis[1]}}</td>
                        <td>{{numVis[2]}}</td>
                        <td>{{numVis[3]}}</td>
                        <td>{{numVis[4]}}</td>
                        <td>{{numVis[5]}}</td>
                        <td>
                            <div class="col-md-2">
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>

                <div class="clearfix"></div>
            </div>

            <legend>{{'reports.numberVisitsWithNPM' | translate}}</legend>
            <div class="table-responsive">
                <table id="numberVisitsWithNPM" class="table table-bordred table-striped">
                    <thead>
                    <tr>
                        <th>{{'reports.table.postId' | translate}}</th>
                        <th>{{'reports.table.title' | translate}}</th>
                        <th>{{'reports.table.utmSource' | translate}}</th>
                        <th>{{'reports.table.utmMedium' | translate}}</th>
                        <th>{{'reports.table.utmCampaign' | translate}}</th>
                        <th>{{'reports.table.utmTerm' | translate}}</th>
                        <th>{{'reports.table.utmContent' | translate}}</th>
                        <th>{{'reports.table.perToday' | translate}}</th>
                        <th>{{'reports.table.thisWeek' | translate}}</th>
                        <th>{{'reports.table.thisMonth' | translate}}</th>
                        <th>{{'reports.table.all' | translate}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr ng-repeat="numVisNPM in rep.numberVisitsWithNPM">
                        <td>{{numVisNPM[0]}}</td>
                        <td>{{numVisNPM[1]}}</td>
                        <td>{{numVisNPM[2]}}</td>
                        <td>{{numVisNPM[3]}}</td>
                        <td>{{numVisNPM[4]}}</td>
                        <td>{{numVisNPM[5]}}</td>
                        <td>{{numVisNPM[6]}}</td>
                        <td>{{numVisNPM[7]}}</td>
                        <td>{{numVisNPM[8]}}</td>
                        <td>{{numVisNPM[9]}}</td>
                        <td>{{numVisNPM[10]}}</td>
                        <td>
                            <div class="col-md-2">
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>

                <div class="clearfix"></div>
            </div>

        </div>
    </div>
</div>

src/main/webapp/resources/settings.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div class="container" ng-controller="Setting as setting">
    <form class="form-horizontal" ng-submit="setting.saveSettings()">
        <fieldset>

            <legend>{{'settings.mainTitle' | translate}}</legend>

            <div class="form-group">
                <label class="col-md-4 control-label" for="passwordinput">{{'settings.newPassword.label' | translate}}</label>
                <div class="col-md-4">
                    <input id="passwordinput" name="passwordinput" type="password" placeholder="{{'settings.newPassword.placeholder' | translate}}"
                           class="form-control input-md" required ng-model="setting.password">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="locale">{{'settings.locale.label' | translate}}</label>
                <div class="col-md-4">
                    <select id="locale" name="locale" class="form-control" ng-model="setting.locale"
                            ng-init="setting.locale='en'">
                        <option value="en">{{'settings.locale.en' | translate}}</option>
                        <option value="uk">{{'settings.locale.uk' | translate}}</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="username">{{'settings.username.label' | translate}}</label>
                <div class="col-md-4">
                    <input id="username" name="username" type="text" placeholder="{{'settings.username.placeholder' | translate}}"
                           class="form-control input-md" ng-model="setting.username">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="gender" ng-model="setting.gender"
                       ng-init="setting.gender='DEFAULT'">{{'settings.gender.label' | translate}}</label>
                <div class="col-md-4">
                    <select id="gender" name="gender" class="form-control">
                        <option value="default">{{'settings.gender.default' | translate}}</option>
                        <option value="male">{{'settings.gender.male' | translate}}</option>
                        <option value="female">{{'settings.gender.female' | translate}}</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="save"></label>
                <div class="col-md-4">
                    <input id="save" name="save" type="submit" value="{{'button.save' | translate}}" class="btn btn-primary"/>
                </div>
            </div>

        </fieldset>
    </form>

</div>

src/main/webapp/resources/singup.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div class="container" ng-controller="SingUp as sgn">
    <legend>{{'singUp.mainTitle' | translate}}</legend>

    <form class="form-signin form-horizontal" ng-submit="sgn.singUp()">
        <div class="form-group">
            <label class="col-md-4 control-label required" for="email">{{'singUp.email.label' | translate}}</label>
            <div class="col-md-4">
                <input id="email" name="email" type="email" placeholder="{{'singUp.email.placeholder' | translate}}"
                       class="form-control input-md" required ng-model="sgn.email">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label required" for="passwordinput">{{'singUp.password.label' | translate}}</label>
            <div class="col-md-4">
                <input id="passwordinput" name="passwordinput" type="password" placeholder="{{'singUp.password.placeholder' | translate}}"
                       class="form-control input-md" required ng-model="sgn.password">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="username">{{'singUp.username.label' | translate}}</label>
            <div class="col-md-4">
                <input id="username" name="username" type="text" placeholder="{{'singUp.username.placeholder' | translate}}"
                       class="form-control input-md" ng-maxlength="100" ng-model="sgn.usernameLM">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="gender">{{'singUp.gender.label' | translate}}</label>
            <div class="col-md-4">
                <select id="gender" name="gender" class="form-control" ng-model="sgn.gender"
                        ng-init="sgn.gender='DEFAULT'">
                    <option value="DEFAULT">{{'singUp.gender.default' | translate}}</option>
                    <option value="MALE">{{'singUp.gender.male' | translate}}</option>
                    <option value="FEMALE">{{'singUp.gender.female' | translate}}</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="age">{{'singUp.age.label' | translate}}</label>
            <div class="col-md-4">
                <input id="age" name="age" type="text" placeholder="{{'singUp.age.placeholder' | translate}}"
                       class="form-control input-md" min="1" max="200" ng-model="sgn.age">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="submit"></label>
            <div class="col-md-4">
                <input id="submit" name="submit" type="submit" value="{{'button.submit' | translate}}" class="btn btn-primary"/>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label"></label>
            <div class="col-md-4">
                {{'singUp.registered' | translate}}<a href="/login"> {{'singUp.loginHere' | translate}}</a>
            </div>
        </div>
    </form>

</div>